services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authms-sql
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - authms-net
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8085:5000"
    networks:
      - authms-net

networks:
  authms-net:
    driver: bridge
