apiVersion: v1
kind: Secret
metadata:
  name: auth-ms-secret
  namespace: auth-ms
type: Opaque
stringData:
 
  # Esta é a string de conexão para o banco de dados
  DB_CONNECTION_STRING: >
    Server=goncalvesc97-fiap-hk-auth-ms-db.c6nwqiks6njl.us-east-1.rds.amazonaws.com,1433;
    Database=AuthDb;
    User Id=admin;
    Password=1q2w3e4r5t;
    Encrypt=True;
    TrustServerCertificate=True;

  # Nome do database
  DB_NAME: "AuthDb"

  # Autenticação nas APIs
  API_AUTH_TOKEN: Yf29qN58VfWbT1YtZz7jRkE4sLt9xP2eUqK3LmXvHsDcMgAjBwNvZxQrFtGvKyLz

