apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms-webapi-deployment
  namespace: auth-ms
  labels:
    app: auth-ms-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms-webapi
  template:
    metadata:
      labels:
        app: auth-ms-webapi
    spec:
      containers:
      - name: auth-ms-webapi
        image: goncalvesc97/fiap-hk-auth-ms:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Configuração do ambiente de banco de dados 
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: auth-ms-secret
              key: DB_CONNECTION_STRING
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: auth-ms-secret
              key: DB_NAME

        # Configuração da chave de autenticação da API
        - name: API_AUTHENTICATION_KEY
          valueFrom:
            secretKeyRef:
              name: auth-ms-secret
              key: API_AUTH_TOKEN