apiVersion: v1
kind: Service
metadata:
  name: auth-ms-webapi-service
  namespace: auth-ms
spec:
  type: LoadBalancer
  selector:
    app: auth-ms-webapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
